//Common
export const SHOW_LOADER = 'show_loader';
export const HIDE_LOADER = 'hide_loader';
export const SHOW_ERROR = 'show_error';
export const CLEAR_ERROR = 'clear_error';
export const SHOW_MESSAGE = 'show_message';
export const CLEAR_MESSAGE = 'clear_message';

//Auth
export const SIGNIN_USER = 'signin_user';
export const SIGNIN_USER_SUCCESS = 'signin_user_success';
export const SIGNOUT_USER = 'signout_user';
export const SIGNOUT_USER_SUCCESS = 'signout_user_success';

//User
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ACTIVATION_CODE = 'ACTIVATION_CODE';
export const ACTIVATION_CODE_SUCCESS = 'ACTIVATION_CODE_SUCCESS';
export const EMAIL_RECOVER_USER = 'EMAIL_RECOVER_USER';
export const EMAIL_RECOVER_USER_SUCCESS = 'EMAIL_RECOVER_USER_SUCCESS';
export const CHANGE_PASSWORD_USER = 'CHANGE_PASSWORD_USER';
export const CHANGE_PASSWORD_USER_SUCCESS = 'CHANGE_PASSWORD_USER_SUCCESS';


//Categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_WITH_PRODUCT = 'GET_CATEGORIES_WITH_PRODUCT';
export const GET_CATEGORIES_WITH_PRODUCT_SUCCESS = 'GET_CATEGORIES_WITH_PRODUCT_SUCCESS';
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES';
export const SEARCH_CATEGORIES_SUCCESS = 'SEARCH_CATEGORIES_SUCCESS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_CATEGORY_SUCCESS = 'SET_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';

//Promotions
export const GET_PROMOTIONS = 'GET_PROMOTIONS';
export const GET_PROMOTIONS_SUCCESS = 'GET_PROMOTIONS_SUCCESS';
export const GET_PROMOTION ='GET_PROMOTION';
export const GET_PROMOTION_SUCCESS ='GET_PROMOTION_SUCCESS';
export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';
export const UPDATE_PROMOTION_SUCCESS = 'UPDATE_PROMOTION_SUCCESS';
export const CREATE_PROMOTION = 'CREATE_PROMOTION';
export const CREATE_PROMOTION_SUCCESS = 'CREATE_PROMOTION_SUCCESS';
export const GET_TOP_PROMOTIONS = 'GET_TOP_PROMOTIONS';
export const GET_TOP_PROMOTIONS_SUCCESS = 'GET_TOP_PROMOTIONS_SUCCESS';
export const SEARCH_PROMOTIONS = 'SEARCH_PROMOTIONS';
export const SEARCH_PROMOTIONS_SUCCESS = 'SEARCH_PROMOTIONS_SUCCESS';

//Preferences
export const CREATE_PREFERENCE = 'CREATE_PREFERENCE';
export const CREATE_PREFERENCE_SUCCESS = 'CREATE_PREFERENCE_SUCCESS';
export const CREATE_GIFT_CARD = 'CREATE_GIFT_CARD';
export const CREATE_GIFT_CARD_SUCCESS = 'CREATE_GIFT_CARD_SUCCESS';
export const CREATE_TOKEN_CARD = 'CREATE_TOKEN_CARD';
export const CREATE_TOKEN_CARD_SUCCESS = 'CREATE_TOKEN_CARD_SUCCESS';

//Payments
export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';

//Inventory
export const CREATE_INVENTORY = 'CREATE_INVENTORY';
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';

//Companies
export const SEARCH_COMPANIES = 'SEARCH_COMPANIES';
export const SEARCH_COMPANIES_SUCCESS = 'SEARCH_COMPANIES_SUCCESS';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';

//Images
export const GET_IMAGES_BY_CONTAINER = 'GET_IMAGES_BY_CONTAINER';
export const GET_IMAGES_BY_CONTAINER_SUCCESS = 'GET_IMAGES_BY_CONTAINER_SUCCESS';

//AuthorizationCode
export const CHECK_CODE = 'CHECK_CODE';
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const REDEEM_CODE = 'REDEEM_CODE';
export const REDEEM_CODE_SUCCESS = 'REDEEM_CODE_SUCCESS';