import React, { Component } from 'react'

export default class PersonalDataProtection extends Component {
    render() {
        return (
            <div className={"data-protection"}>
                Conforme a la Ley 1581 de 2012 y al Decreto 1377 de 2013, SANAUTOS S.A., en adelante “SANAUTOS”, considerada como Responsable y/o Encargada del tratamiento de datos personales que almacena y recolecta de sus clientes en desarrollo de sus actividades comerciales, de ventas de sus productos en su red de almacenes o en los canales en línea, o en eventos promocionales, entre otros, requiere obtener su autorización para continuar con el tratamiento de sus datos personales conforme a la política de privacidad para el tratamiento de sus datos personales las cuales están disponibles en www.sanautos.com.co Esta información suministrada podrá ser procesada, recolectada, almacenada, usada, circulada, suprimida, compartida, actualizada, transmitida y/o transferida a terceros países de acuerdo y conforme a nuestras políticas de tratamiento y con el fin de continuar desarrollando nuestras actividades comerciales y promocionales para mantenerlo informado acerca de novedades en nuestros productos, promociones, ofertas y en general, acerca de cualquier aspecto relacionado con nuestra actividad comercial. SANAUTOS , en los términos dispuestos por el artículo 10 del decreto 1377 de 2013 queda autorizada de manera expresa e inequívoca para mantener y manejar su información, a no ser que usted le manifieste lo contrario de manera directa, expresa o inequívoca, por escrito, a la dirección de correo electrónico dispuesta para tal efecto servicioalcliente@Sanautos.com.co o llamando a la línea de atención No. 5557077, dentro de los treinta (30) días hábiles contados a partir de la recepción de la presente comunicación. Para conocer nuestras políticas de tratamiento y el modo en que puede ejercer sus derechos de conocer, actualizar, rectificar y suprimir por favor consulte nuestra página web www.sanautos.com.co o escribanos al siguiente correo electrónico comunicaciones@sanautos.com.co Por consiguiente, Sanautos, como responsable del tratamiento de datos personales, pone a disposición de los titulares de la información que actualmente tiene en sus bases de datos, la solicitud de autorización para llevar a cabo el tratamiento de sus datos personales como es la recolección, almacenamiento, uso, circulación, transferencia y/o recepción de datos, lo cual realizará a través de su Departamento de Mercadeo, Agencia de Seguros y/o sus aliados comerciales o de negocios, con el fin de permitir el contacto de los Clientes para evaluar la calidad de los productos y servicios Renault, informar de manera oportuna a sus clientes los nuevos productos y servicios, así como los beneficios a los que pueden acceder mediante las diferentes actividades y promociones desplegadas por la Compañía y la marca Renault.
            </div>
        )
    }
}
